### ISSUE TITLE
Problems when reading Run_Settings.txt depending on the DESY_MOVING_TABLE configuration

### ISSUE THREAD

**Issue by kunathj** [SiWECAL-TestBeam/SiWECAL-TB-analysis#19]
This issue concerns the changes introduced with commit https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/commit/bc168b77b400805f4c19cdebc151d3d0dc9e4dfa.
It concerns the `DESY_MOVING_TABLE` line in the `Run_Settings.txt` files.
I have seen three situations in the test beam data:

1. There is no `DESY_MOVING_TABLE` line. 
   - e.g. run_050018
2. The line is written, with the table position.
   - e.g. 3GeVMIPscan_run_050039
   - `== DESY_MOVING_TABLE: CONNECTED LAST_SET_X_POSITION: -800 LAST_SET_Y_POSITION 800 LAST_READ_X_POSITION: -791 LAST_READ_Y_POSITION: 602 ==`
3. The line is written, without a table position. 
   - e.g. 5GeV_W_run_050158
   - `== DESY_MOVING_TABLE: NOT_CONNECTED ==`

Before the mentioned commit, the line was not expected to exist.
Thus, the code behaved as expected in case 1.
Cases 2 and 3  lead to unusable configuration readings.

After the mentioned commit, case 2 is properly handled.
Case 3 still does not work, as it has a different number of fields (white space separated words).
Case 1 does no longer work, as it has no `DESY_MOVING_TABLE` line.

I collected some quick statistics on the occurrence of each case in our 199 recorded runs.
  
| Case | scenario          |   #    |
|---------|:--------------------|------:|
| 1.       | no line             |  32  |
| 2.       | connected       |  39  |
| 3.       | not connected | 128 |

I would propose to do one of the following:
1. Remove the `DESY_MOVING_TABLE` lines in all files from the test beam. Then revert the mentioned commit.
2. Add/replace a line in cases 1 and 3, so that they appear like case 2.
3. Properly handle all 3 cases in the code.
4. Leave the handling of this to the end user. 

From my side, this issue is not urgent and the discussion can wait until the Analysis meeting on Tuesday.

**Comment by airqui** [comment]
Hi @kunathj , yes, this is an issue introduced during the beam test.
The only reasonable way to do it is your option 3).
@yuichiok is taking care of implementing this.

Anyway, the runs before the desy table was connected are not very useful, these are all test runs and find beam runs etc. So, there are only 2 cases.

**Comment by kunathj** [comment]
Great. I would leave this open until @yuichiok's fix is shipped.
But you can of course use your maintainer powers to close this whenever you want.

**Comment by airqui** [comment]
No, no, leave it open. I am sure that he will find useful your summary :)

**Comment by yuichiok** [comment]
I am a week late but the problem is permanently fixed, I think.
I made a pull request. With this version, it is very easy to extract stage position as well but it is not included in this version because I am not sure we need stage position information at the moment..
