### ISSUE TITLE
Covariance matrix fit: Missing entries for bad fits

### ISSUE THREAD

**Issue by kunathj** [SiWECAL-TestBeam/SiWECAL-TB-analysis#26]
The pedestal calibration with he noise covariance matrix yields inconsistent output.
In the first if-clause, only 4 out of the 5 necessary fields are filled:

https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/blob/b888d2a9783e97a2858e252bb624cc620f6d1775/SLBperformance/noise_covariance_matrix/analysis/SummaryPlots.C#L238

In all other cases, the number of fields consistent with the header (5) is filled, e.g.:
https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/blob/b888d2a9783e97a2858e252bb624cc620f6d1775/SLBperformance/noise_covariance_matrix/analysis/SummaryPlots.C#L249

I am not sure if the correct behaviour is to fill this value with `-5` or with `pedrmsv_[isca]`. Else I would have submitted a PR.

## Necessary changes for `Pedestal_method2_3GeVMIPscan_highgain.txt` and `Pedestal_method2_3GeVMIPscan_lowgain.txt`

For my personal use (python eventbuilding), it is enough to just create a copy of the pedestal calibration files and replace each stand-alone `-5` with `-5 -5`.
I propose to replace the calibration files on the `eos` by this version, if @airqui agrees.
The alternative would be to rerun the calibration code, after this bug is fixed.

**Comment by airqui** [comment]
ups... 
I screwed it!
can you replace the files yourself ? But not close this issue so I won't forget to (eventually) solve the bug in the calibration code

**Comment by kunathj** [comment]
Tangentially related:

With the method2, one of the high_gain chips (layer 3, chip 15) has no valid fits for any channel.
For channels without a failed fit, I currently take the average of the valid channels on _that_ chip.
If there is no valid channels, this defaults to zero, and thus a divide by zero. 

What would be better behaviour? Set mip_value to `1` on this chip (just to avoid the divide-by-zero)?
Take the average on the slab? But then what should be done if the whole slab has no valid fits?

**Comment by airqui** [comment]
I don't know...
The thing is that this associated to an ill-circumstance: the HV was disconnected for this layer most of the time, hence the data is anyway useless.

I would propose to use the mip_value=1 just to circumvent this issue. Maybe showing a message to be aware.

In normal circumstances this should not happen.

**Comment by airqui** [comment]
Or maybe even divide by 10000 instead of by 1... if the charge is wrong, it is better wrong but very small than wrong but large.

**Comment by kunathj** [comment]
> can you replace the files yourself ?

It is replaced on the eos now

> Or maybe even divide by 10000 

Great idea! Division by a large value is the least "harmful" for any quick visualizations.
In any case, this of course has an `is_commissioned == 0` flag, so users could see that something weird was going, given that the whole chip has this flag.

I'll prepare that tiny bug-fix PR for the division by zero now..

**Comment by airqui** [comment]
thanks :)

**Comment by airqui** [comment]
This is solved, right ?

**Comment by kunathj** [comment]
>  But not close this issue so I won't forget to (eventually) solve the bug in the calibration code

I waited for this. But seems fixed now:

https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/blob/94cd57a0851f1e2292f26113fdb050181e68c16a/SLBperformance/noise_covariance_matrix/analysis/SummaryPlots.C#L102

I believe you sneaked the fix into the codebase here: https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/commit/c81171dac126322451e45005d766078caf54b532#r71000747

From my side, this can be closed.
